name: Update gist with new hitokoto

on:
  push:
    branches: [ k ]
  schedule:
    - cron: "0 * * * *"
jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GIST_ID: 8e67db8b8b1bfd06982ac0557f85e8a2
      CATEGORY: k
    steps:
    - uses: actions/checkout@v3
      with:
        ref: k

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Check out
      uses: actions/checkout@v2

    - name: Update gist
      run: go run .
